from __future__ import annotations


SOURCE_TYPES = [
    {
        "value": "paid_ads",
        "label": "Paid ads",
        "meaning": "Le prospect vient d'une campagne payante, par exemple Google Ads, Meta Ads ou Bing Ads.",
    },
    {
        "value": "organic",
        "label": "Recherche naturelle",
        "meaning": "Le prospect vient d'une recherche naturelle et arrive généralement comme préinscription.",
    },
    {
        "value": "mock",
        "label": "Mock local",
        "meaning": "Donnée de démonstration locale.",
    },
    {
        "value": "schooldrive_webhook",
        "label": "SchoolDrive webhook",
        "meaning": "Donnée reçue automatiquement depuis SchoolDrive.",
    },
    {
        "value": "unknown",
        "label": "Inconnu",
        "meaning": "Origine non encore synchronisée.",
    },
]

QUALIFICATION_STATUSES = [
    {
        "value": "eligible",
        "label": "Éligible",
        "meaning": "Qualification par défaut : le prospect peut continuer dans le parcours commercial.",
        "stops_followups": False,
    },
    {
        "value": "not_relevant",
        "label": "Non pertinent",
        "meaning": "Le prospect ne correspond pas à une opportunité commerciale utile.",
        "stops_followups": True,
    },
    {
        "value": "will_sign",
        "label": "Va signer",
        "meaning": "Le closer estime que le prospect va signer, relance dédiée à activer.",
        "stops_followups": False,
    },
    {
        "value": "signed",
        "label": "A signé",
        "meaning": "La vente est gagnée, les relances commerciales s'arrêtent.",
        "stops_followups": True,
    },
]

CONTACT_STATUSES = [
    {
        "value": "contact_allowed",
        "label": "Contact autorisé",
        "meaning": "Le prospect peut être contacté dans le respect des règles WhatsApp.",
        "stops_followups": False,
    },
    {
        "value": "do_not_contact",
        "label": "Ne plus contacter",
        "meaning": "Le prospect a demandé à ne plus être contacté. Aucune relance automatique ne doit être créée.",
        "stops_followups": True,
    },
]

STOP_QUALIFICATION_STATUSES = {
    item["value"] for item in QUALIFICATION_STATUSES if item["stops_followups"]
}
STOP_CONTACT_STATUSES = {
    item["value"] for item in CONTACT_STATUSES if item["stops_followups"]
}
STOP_FOLLOWUP_STATUSES = STOP_QUALIFICATION_STATUSES | STOP_CONTACT_STATUSES

RESOLUTION_REASONS = [
    {
        "value": "signed",
        "label": "Signé",
        "meaning": "Le prospect a signé. La vente est gagnée.",
        "requires_note": False,
    },
    {
        "value": "not_relevant",
        "label": "Non pertinent",
        "meaning": "Le prospect n'est pas une opportunité commerciale utile.",
        "requires_note": False,
    },
    {
        "value": "do_not_contact",
        "label": "Ne plus contacter",
        "meaning": "Le prospect a demandé à ne plus être contacté.",
        "requires_note": True,
    },
    {
        "value": "duplicate",
        "label": "Doublon",
        "meaning": "La demande existe déjà ailleurs.",
        "requires_note": False,
    },
    {
        "value": "handled_elsewhere",
        "label": "Traité ailleurs",
        "meaning": "Le dossier est traité hors de cette conversation.",
        "requires_note": True,
    },
    {
        "value": "sequence_completed_no_reply",
        "label": "Suivi terminé sans réponse",
        "meaning": "La dernière relance prévue a été envoyée et le prospect n'a pas répondu.",
        "requires_note": False,
    },
    {
        "value": "error",
        "label": "Erreur",
        "meaning": "La conversation ou le lead a été créé par erreur.",
        "requires_note": True,
    },
    {
        "value": "other",
        "label": "Autre",
        "meaning": "Cas non couvert par les motifs standard.",
        "requires_note": True,
    },
]

TEMPLATE_REQUEST_STATUSES = [
    {"value": "to_create", "label": "À créer"},
    {"value": "submitted", "label": "Soumis"},
    {"value": "approved", "label": "Approuvé"},
    {"value": "rejected", "label": "Rejeté"},
    {"value": "cancelled", "label": "Annulé"},
]

SALES_ACTORS = [
    {
        "code": "setter_1",
        "label": "Setter I",
        "person": "Mihary",
        "email": "service.etudiants@essr.ch",
        "responsibility": "Conversation écrite active, revue des messages entrants et appel de setting.",
        "automation": "Humain en V1",
        "Tâches": True,
        "Inbox": True,
        "Modèles": True,
        "Mode d'emploi": True,
        "Admin": False,
    },
    {
        "code": "setter_2",
        "label": "Setter II",
        "person": "Tanjona",
        "email": "setter2@essr.ch",
        "responsibility": "Relances structurées par template, hors conversation active.",
        "automation": "Candidat prioritaire à l'automatisation après V1",
        "Tâches": True,
        "Inbox": True,
        "Modèles": True,
        "Mode d'emploi": True,
        "Admin": False,
    },
    {
        "code": "closer",
        "label": "Closer",
        "person": "Yasmine",
        "email": "yasmine@essr.ch",
        "responsibility": "Closing téléphonique et qualification de closing.",
        "automation": "Humain",
        "Tâches": True,
        "Inbox": True,
        "Modèles": True,
        "Mode d'emploi": True,
        "Admin": False,
    },
]

OPERATING_RULES = [
    {
        "rule": "Origine formulaire",
        "value": "Le prospect remplit un formulaire web. SchoolDrive crée ensuite le Lead ou la Préinscription.",
        "effect": "Le cockpit reçoit le lead depuis SchoolDrive et ne remplace pas SchoolDrive comme source de vérité.",
    },
    {
        "rule": "Lead vs Préinscription",
        "value": "Les Leads viennent principalement des paid ads. Les Préinscriptions viennent principalement du trafic organique.",
        "effect": "Le type SchoolDrive influence l'affichage cours/catégorie et les rappels liés au début de session.",
    },
    {
        "rule": "Fenêtre WhatsApp",
        "value": "Ouverte 24h après chaque message entrant du prospect.",
        "effect": "Message libre possible uniquement pendant cette fenêtre.",
    },
    {
        "rule": "Premier template automatique",
        "value": "Envoyé par SchoolDrive/Twilio à la création du lead.",
        "effect": "N'ouvre pas la fenêtre WhatsApp tant que le prospect ne répond pas.",
    },
    {
        "rule": "Relances hors fenêtre",
        "value": "Template approuvé obligatoire.",
        "effect": "Setter II relit la conversation, choisit le template approprié ou demande un nouveau template.",
    },
    {
        "rule": "Délai minimum WhatsApp",
        "value": "24h entre deux relances sortantes.",
        "effect": "Une relance concurrente trop proche doit être annulée ou repoussée.",
    },
    {
        "rule": "Conflit lead vs cours",
        "value": "La relance liée à une date de cours gagne contre une relance lead/préinscription concurrente.",
        "effect": "La relance liée au cycle du lead est annulée, sauf si un appel setting ou closing est déjà planifié.",
    },
    {
        "rule": "Message entrant pendant appel planifié",
        "value": "Le prospect peut écrire alors qu'un appel setting ou closing est déjà prévu.",
        "effect": "Créer une réponse urgente pour Setter I sans annuler l'appel planifié. Après réponse simple, l'appel reste la prochaine action.",
    },
    {
        "rule": "Non pertinent",
        "value": "Qualification commerciale négative.",
        "effect": "Fin du process et arrêt des relances.",
    },
    {
        "rule": "Ne plus contacter",
        "value": "Statut de contact séparé de la qualification commerciale.",
        "effect": "Blocage strict des relances. Si le prospect réécrit, une revue Setter I est créée.",
    },
    {
        "rule": "Automatisation V1",
        "value": "Le cockpit crée les tâches de relance mais n'envoie pas automatiquement les templates.",
        "effect": "L'automatisation des relances est gardée pour V2.",
    },
]

SCHEDULE_RULES = [
    {
        "rule": "Horaires entreprise",
        "value": "Lundi-vendredi 08:00-20:00, fuseau Europe/Zurich. Samedi, dimanche et jours fériés fermés.",
        "effect": "Base commune pour décider si une réponse doit être immédiate, différée au prochain créneau ouvré ou confiée à un backup.",
    },
    {
        "rule": "Horaires Setter I",
        "value": "Mihary, lundi-vendredi 08:00-17:00, fuseau Europe/Zurich.",
        "effect": "Si Mihary est absent, ses tâches basculent vers Yasmine.",
    },
    {
        "rule": "Horaires Setter II",
        "value": "Tanjona, lundi-vendredi 12:00-16:00, fuseau Europe/Zurich.",
        "effect": "Si Tanjona est absente, ses tâches attendent.",
    },
    {
        "rule": "Horaires Closer",
        "value": "Yasmine, lundi-vendredi 11:00-20:00, fuseau Europe/Zurich.",
        "effect": "Si Yasmine est absente, ses tâches attendent.",
    },
    {
        "rule": "Absences et backups",
        "value": "Mihary absent -> Yasmine. Yasmine absente -> attente. Tanjona absente -> attente.",
        "effect": "Transférer la prochaine action à un backup sans changer sa nature ni perdre l'historique.",
    },
    {
        "rule": "Répondeur hors horaire",
        "value": "V1 provisoire à valider : utiliser le modèle `demo_out_of_hours_ack` si un accusé de réception est nécessaire.",
        "effect": "Informer le prospect qu'un retour sera fait au prochain créneau ouvré et planifier la vraie réponse.",
    },
]

ASSIGNMENT_RULES = [
    {
        "trigger": "message entrant standard",
        "owner": "Setter I",
        "effect": "Le prospect passe en haut de la file Setter I avec une action Répondre.",
    },
    {
        "trigger": "message entrant d'un prospect Ne plus contacter",
        "owner": "Setter I",
        "effect": "Créer une revue de statut de contact. Aucune relance automatique.",
    },
    {
        "trigger": "relance structurée",
        "owner": "Setter II",
        "effect": "Relire la conversation, choisir le template et envoyer manuellement en V1.",
    },
    {
        "trigger": "passage au closing",
        "owner": "Closer",
        "effect": "Créer une action Appel de closing pour Closer.",
    },
    {
        "trigger": "responsable absent",
        "owner": "Backup configuré",
        "effect": "Transférer l'action sans changer sa nature ni son historique.",
    },
]

SEQUENCES = [
    {
        "code": "lead_no_reply",
        "label": "Lead sans réponse initiale",
        "timeline": "Relative au message automatique initial",
        "trigger": "Template automatique envoyé, aucun message entrant du prospect.",
        "owner": "Setter II",
        "stop_when": "Réponse entrante, non pertinent, ne plus contacter, signé.",
    },
    {
        "code": "setter_no_next_step",
        "label": "Échange setter sans suite",
        "timeline": "Relative au dernier message sortant ou échange setter",
        "trigger": "Setter I a échangé, aucun RDV posé et 72h sans échange.",
        "owner": "Setter II",
        "stop_when": "Réponse entrante, RDV posé, non pertinent, ne plus contacter.",
    },
    {
        "code": "setting_call_not_reached",
        "label": "No-show setting",
        "timeline": "Relative à la tentative d'appel setting",
        "trigger": "Setter I n'a pas pu joindre le prospect lors d'un appel setting.",
        "owner": "Setter I puis Setter II",
        "stop_when": "Prospect joint, réponse entrante, non pertinent, ne plus contacter.",
    },
    {
        "code": "closing_call_not_reached",
        "label": "No-show closing",
        "timeline": "Relative à la tentative d'appel closing",
        "trigger": "Closer n'a pas pu joindre le prospect.",
        "owner": "Closer puis Setter II",
        "stop_when": "Prospect joint, réponse entrante, signé, non pertinent, ne plus contacter.",
    },
    {
        "code": "post_setting_undecided",
        "label": "Post-appel setting indécis",
        "timeline": "Relative à l'appel setting terminé",
        "trigger": "Le prospect a été joint au setting mais aucun closing ou statut terminal n'est fixé.",
        "owner": "Setter II",
        "stop_when": "Réponse entrante, RDV posé, signature, non pertinent, ne plus contacter.",
    },
    {
        "code": "post_closing_undecided",
        "label": "Post-appel closing indécis",
        "timeline": "Relative à l'appel closing terminé",
        "trigger": "Le prospect a été joint au closing mais aucune décision claire n'est prise.",
        "owner": "Setter II",
        "stop_when": "Réponse entrante, RDV posé, signature, non pertinent, ne plus contacter.",
    },
    {
        "code": "closer_will_sign",
        "label": "Closer : va signer",
        "timeline": "Relative à la qualification closer",
        "trigger": "Closer qualifie le prospect en Va signer.",
        "owner": "Setter II",
        "stop_when": "Signature, réponse entrante nécessitant humain, ne plus contacter.",
    },
    {
        "code": "course_start",
        "label": "Début de cours",
        "timeline": "Relative au cours",
        "trigger": "Date de début de session connue dans SchoolDrive.",
        "owner": "Setter II ou automatisation",
        "stop_when": "Signature, non pertinent, ne plus contacter.",
    },
]

SEQUENCE_STEPS = [
    {
        "sequence_code": "lead_no_reply",
        "step_index": 1,
        "delay": "+72h",
        "template_name": "demo_relance_72h_1",
        "meaning": "Première relance après le message automatique initial.",
    },
    {
        "sequence_code": "lead_no_reply",
        "step_index": 2,
        "delay": "+72h",
        "template_name": "demo_relance_72h_2",
        "meaning": "Deuxième relance 72h après la relance précédente.",
    },
    {
        "sequence_code": "lead_no_reply",
        "step_index": 3,
        "delay": "+72h",
        "template_name": "demo_relance_72h_3",
        "meaning": "Troisième relance 72h après la relance précédente.",
    },
    {
        "sequence_code": "lead_no_reply",
        "step_index": 4,
        "delay": "+7j",
        "template_name": "demo_relance_7j_1",
        "meaning": "Relance espacée une semaine après la troisième relance.",
    },
    {
        "sequence_code": "lead_no_reply",
        "step_index": 5,
        "delay": "+7j",
        "template_name": "demo_relance_7j_2",
        "meaning": "Dernière relance courte une semaine après la précédente.",
    },
    {
        "sequence_code": "lead_no_reply",
        "step_index": 6,
        "delay": "+30j",
        "template_name": "demo_relance_30j_stop",
        "meaning": "Relance finale avant résolution sans réponse.",
    },
    {
        "sequence_code": "setter_no_next_step",
        "step_index": 1,
        "delay": "+72h",
        "template_name": "demo_relance_setting_72h_1",
        "meaning": "Relance après échange setter sans rendez-vous.",
    },
    {
        "sequence_code": "setter_no_next_step",
        "step_index": 2,
        "delay": "+72h",
        "template_name": "demo_relance_setting_72h_2",
        "meaning": "Deuxième relance après échange setter sans rendez-vous.",
    },
    {
        "sequence_code": "setter_no_next_step",
        "step_index": 3,
        "delay": "+72h",
        "template_name": "demo_relance_setting_72h_3",
        "meaning": "Troisième relance après échange setter sans rendez-vous.",
    },
    {
        "sequence_code": "setter_no_next_step",
        "step_index": 4,
        "delay": "+7j",
        "template_name": "demo_relance_setting_7j_1",
        "meaning": "Relance espacée une semaine.",
    },
    {
        "sequence_code": "setter_no_next_step",
        "step_index": 5,
        "delay": "+7j",
        "template_name": "demo_relance_setting_7j_2",
        "meaning": "Dernière relance courte avant relance finale.",
    },
    {
        "sequence_code": "setter_no_next_step",
        "step_index": 6,
        "delay": "+30j",
        "template_name": "demo_relance_setting_30j_stop",
        "meaning": "Relance finale avant résolution sans réponse.",
    },
    {
        "sequence_code": "setting_call_not_reached",
        "step_index": 1,
        "delay": "+2h ouvrées",
        "template_name": "",
        "meaning": "Rappel 1 setting : rappeler le prospect après un appel setting non joint.",
    },
    {
        "sequence_code": "setting_call_not_reached",
        "step_index": 2,
        "delay": "+24h ouvrées",
        "template_name": "",
        "meaning": "Rappel 2 setting : dernière tentative téléphonique avant bascule en relance.",
    },
    {
        "sequence_code": "setting_call_not_reached",
        "step_index": 3,
        "delay": "+72h",
        "template_name": "demo_relance_setting_72h_1",
        "meaning": "Relance WhatsApp après trois appels setting non joints.",
    },
    {
        "sequence_code": "closing_call_not_reached",
        "step_index": 1,
        "delay": "+2h ouvrées",
        "template_name": "",
        "meaning": "Rappel 1 closing : rappeler le prospect après un appel closing non joint.",
    },
    {
        "sequence_code": "closing_call_not_reached",
        "step_index": 2,
        "delay": "+24h ouvrées",
        "template_name": "",
        "meaning": "Rappel 2 closing : dernière tentative téléphonique avant bascule en relance.",
    },
    {
        "sequence_code": "closing_call_not_reached",
        "step_index": 3,
        "delay": "+72h",
        "template_name": "demo_va_signer_72h_1",
        "meaning": "Relance WhatsApp après trois appels closing non joints.",
    },
    {
        "sequence_code": "post_setting_undecided",
        "step_index": 1,
        "delay": "+72h",
        "template_name": "demo_relance_72h_1",
        "meaning": "Relance après appel setting où le prospect a été joint mais reste indécis.",
    },
    {
        "sequence_code": "post_closing_undecided",
        "step_index": 1,
        "delay": "+72h",
        "template_name": "demo_va_signer_72h_1",
        "meaning": "Relance après appel closing où le prospect a été joint mais reste indécis.",
    },
    {
        "sequence_code": "closer_will_sign",
        "step_index": 1,
        "delay": "+72h",
        "template_name": "demo_va_signer_72h_1",
        "meaning": "Première relance après qualification closer Va signer.",
    },
    {
        "sequence_code": "closer_will_sign",
        "step_index": 2,
        "delay": "+72h",
        "template_name": "demo_va_signer_72h_2",
        "meaning": "Deuxième relance Va signer.",
    },
    {
        "sequence_code": "closer_will_sign",
        "step_index": 3,
        "delay": "+72h",
        "template_name": "demo_va_signer_72h_3",
        "meaning": "Troisième relance Va signer.",
    },
    {
        "sequence_code": "closer_will_sign",
        "step_index": 4,
        "delay": "+7j",
        "template_name": "demo_va_signer_7j_1",
        "meaning": "Relance espacée une semaine pour finaliser.",
    },
    {
        "sequence_code": "closer_will_sign",
        "step_index": 5,
        "delay": "+7j",
        "template_name": "demo_va_signer_7j_2",
        "meaning": "Dernière relance courte pour finaliser.",
    },
    {
        "sequence_code": "closer_will_sign",
        "step_index": 6,
        "delay": "+30j",
        "template_name": "demo_va_signer_30j_stop",
        "meaning": "Relance finale Va signer avant résolution.",
    },
    {
        "sequence_code": "course_start",
        "step_index": 1,
        "delay": "J-14",
        "template_name": "demo_cours_j14",
        "meaning": "Relance cours deux semaines avant le début.",
    },
    {
        "sequence_code": "course_start",
        "step_index": 2,
        "delay": "J-7",
        "template_name": "demo_cours_j7",
        "meaning": "Relance cours une semaine avant le début.",
    },
    {
        "sequence_code": "course_start",
        "step_index": 3,
        "delay": "J-3",
        "template_name": "demo_cours_j3",
        "meaning": "Relance cours trois jours avant le début.",
    },
    {
        "sequence_code": "course_start",
        "step_index": 4,
        "delay": "J-1",
        "template_name": "demo_cours_j1",
        "meaning": "Relance cours la veille du début.",
    },
]

MAIN_ACTION_TYPES = [
    {
        "type": "reply",
        "label": "Répondre",
        "meaning": "Répondre à un message entrant WhatsApp.",
        "default_owner": "Setter I",
        "expected_proof": "Message WhatsApp sortant après le message entrant.",
    },
    {
        "type": "follow_up",
        "label": "Relancer",
        "meaning": "Relancer le prospect, souvent via template WhatsApp.",
        "default_owner": "Setter II",
        "expected_proof": "Message libre ou template de relance envoyé.",
    },
    {
        "type": "setting_call",
        "label": "Documenter appel setting",
        "meaning": "Appeler puis documenter le résultat, la mini note et la suite commerciale.",
        "default_owner": "Setter I",
        "expected_proof": "Résultat d'appel, mini note et qualification setter.",
    },
    {
        "type": "closing_call",
        "label": "Documenter appel closing",
        "meaning": "Appeler puis documenter le résultat, la mini note et la qualification de closing.",
        "default_owner": "Closer",
        "expected_proof": "Résultat d'appel, mini note et qualification closer.",
    },
]

SUPPORT_ACTIONS = [
    {
        "support": "Qualification",
        "role": "Résultat métier qui influence le chaînage. La qualification closer prime sur celle du setter.",
        "queue_visible_when": "Seulement si une revue de qualification bloque le flux.",
    },
    {
        "support": "Statut de contact",
        "role": "Décide si le prospect peut encore être contacté.",
        "queue_visible_when": "Quand un prospect Ne plus contacter réécrit et nécessite une revue Setter I.",
    },
    {
        "support": "Note manuelle",
        "role": "Preuve ou contexte après appel, échange privé ou décision.",
        "queue_visible_when": "Seulement si une documentation obligatoire manque.",
    },
    {
        "support": "Création de template",
        "role": "Débloque une relance quand aucun template approuvé ne convient.",
        "queue_visible_when": "Quand une relance est bloquée par template manquant.",
    },
    {
        "support": "Revue admin",
        "role": "Cas ambigu, conflit de règles ou donnée manquante.",
        "queue_visible_when": "Quand le système ne peut pas choisir la prochaine action.",
    },
]

ACTION_STATUSES = [
    {
        "status": "planned",
        "label": "Planifiée",
        "meaning": "Action prévue plus tard.",
        "is_terminal": False,
    },
    {
        "status": "open",
        "label": "Ouverte",
        "meaning": "Action active.",
        "is_terminal": False,
    },
    {
        "status": "in_progress",
        "label": "En cours",
        "meaning": "Quelqu'un a pris l'action en main.",
        "is_terminal": False,
    },
    {
        "status": "done",
        "label": "Terminée",
        "meaning": "Action terminée avec preuve ou résultat.",
        "is_terminal": True,
    },
    {
        "status": "cancelled",
        "label": "Annulée",
        "meaning": "Action remplacée, rendue inutile ou annulée par une règle.",
        "is_terminal": True,
    },
    {
        "status": "blocked",
        "label": "Bloquée",
        "meaning": "Action impossible tant qu'un blocage n'est pas levé.",
        "is_terminal": False,
    },
]

WORKFLOW_TRANSITIONS = [
    {
        "current_action": "Aucune",
        "trigger": "web_form_submitted_then_schooldrive_lead_created",
        "outcome": "SchoolDrive crée un Lead ou une Préinscription et envoie le WhatsApp automatique initial",
        "next_action": "follow_up",
        "owner": "Setter II",
        "due": "+72h après le WhatsApp automatique initial",
        "conversation": "Ouverte",
        "required_support": "Identifiant SchoolDrive, type lead/presubscription, source paid_ads/organic",
        "side_effects": "Stocker l'événement initial et annuler cette relance si le prospect répond avant échéance",
    },
    {
        "current_action": "follow_up",
        "trigger": "initial_message_no_reply_after_72h",
        "outcome": "Le prospect n'a pas répondu au WhatsApp automatique initial",
        "next_action": "follow_up",
        "owner": "Setter II",
        "due": "Maintenant",
        "conversation": "Ouverte",
        "required_support": "Relire conversation, choisir template approuvé ou créer template_request",
        "side_effects": "Respecter délai minimum 24h entre relances WhatsApp",
    },
    {
        "current_action": "Toute action non terminale",
        "trigger": "prospect_replied",
        "outcome": "Dernier message entrant non répondu et contact autorisé",
        "next_action": "reply",
        "owner": "Setter I",
        "due": "Maintenant",
        "conversation": "Ouverte",
        "required_support": "Aucun",
        "side_effects": "Hot signal, file Setter I, annuler relances futures, garder tout appel déjà planifié",
    },
    {
        "current_action": "Toute action non terminale",
        "trigger": "do_not_contact_prospect_replied",
        "outcome": "Le prospect est Ne plus contacter mais réécrit",
        "next_action": "contact_review",
        "owner": "Setter I",
        "due": "Maintenant",
        "conversation": "Ouverte",
        "required_support": "Revue humaine obligatoire",
        "side_effects": "Aucune relance automatique tant que le blocage n'est pas levé",
    },
    {
        "current_action": "reply",
        "trigger": "outbound_message_sent",
        "outcome": "Réponse envoyée sans RDV et aucun appel déjà planifié",
        "next_action": "follow_up",
        "owner": "Setter II",
        "due": "+72h après le dernier message sortant",
        "conversation": "Ouverte",
        "required_support": "Message sortant",
        "side_effects": "Supprimer hot signal",
    },
    {
        "current_action": "reply",
        "trigger": "outbound_message_sent",
        "outcome": "Réponse envoyée pendant qu'un appel est déjà planifié",
        "next_action": "appel déjà planifié",
        "owner": "Responsable de l'appel",
        "due": "Date/heure RDV",
        "conversation": "Ouverte",
        "required_support": "Message sortant",
        "side_effects": "Clore la réponse sans créer de relance Setter II parallèle",
    },
    {
        "current_action": "reply",
        "trigger": "setting_appointment_booked",
        "outcome": "RDV setting fixé",
        "next_action": "setting_call",
        "owner": "Setter I",
        "due": "Date/heure RDV",
        "conversation": "Ouverte",
        "required_support": "Message sortant, RDV noté",
        "side_effects": "Annuler relance de sécurité",
    },
    {
        "current_action": "reply",
        "trigger": "written_exchange_terminal",
        "outcome": "Prospect non pertinent ou Ne plus contacter",
        "next_action": "Aucune",
        "owner": "Personne",
        "due": "Aucun",
        "conversation": "Résolue",
        "required_support": "Qualification ou statut de contact",
        "side_effects": "Stopper relances",
    },
    {
        "current_action": "follow_up",
        "trigger": "follow_up_due",
        "outcome": "Fenêtre WhatsApp ouverte",
        "next_action": "Selon résultat de l'envoi",
        "owner": "Setter II",
        "due": "Maintenant",
        "conversation": "Ouverte",
        "required_support": "Message libre ou template",
        "side_effects": "Respecter délai minimum",
    },
    {
        "current_action": "follow_up",
        "trigger": "follow_up_due",
        "outcome": "Fenêtre WhatsApp fermée, template disponible",
        "next_action": "Selon résultat de l'envoi",
        "owner": "Setter II",
        "due": "Maintenant",
        "conversation": "Ouverte",
        "required_support": "Template approuvé",
        "side_effects": "Respecter délai minimum",
    },
    {
        "current_action": "follow_up",
        "trigger": "follow_up_due_template_missing",
        "outcome": "Fenêtre fermée et aucun template adapté",
        "next_action": "follow_up bloquée",
        "owner": "Setter II",
        "due": "Maintenant",
        "conversation": "Ouverte",
        "required_support": "template_request",
        "side_effects": "Action principale passe blocked et reste liée à la demande de template",
    },
    {
        "current_action": "template_request",
        "trigger": "template_submitted",
        "outcome": "Nouveau template soumis à validation",
        "next_action": "follow_up reste bloquée",
        "owner": "Setter II",
        "due": "Dès approbation",
        "conversation": "Ouverte",
        "required_support": "Statut Twilio/Meta",
        "side_effects": "Surveiller statut template",
    },
    {
        "current_action": "template_request",
        "trigger": "template_approved",
        "outcome": "Relance débloquée",
        "next_action": "follow_up",
        "owner": "Setter II",
        "due": "Maintenant",
        "conversation": "Ouverte",
        "required_support": "Template approuvé",
        "side_effects": "Débloquer action principale",
    },
    {
        "current_action": "follow_up",
        "trigger": "outbound_template_sent",
        "outcome": "Relance envoyée, flux non terminé",
        "next_action": "follow_up",
        "owner": "Setter II",
        "due": "Selon prochaine étape du flux",
        "conversation": "Ouverte",
        "required_support": "Message sortant",
        "side_effects": "Avancer dans le flux",
    },
    {
        "current_action": "follow_up",
        "trigger": "outbound_template_sent_last_step",
        "outcome": "Dernière relance du flux envoyée sans réponse",
        "next_action": "Aucune",
        "owner": "Personne",
        "due": "Aucun",
        "conversation": "Résolue",
        "required_support": "Message sortant",
        "side_effects": "Motif résolution sequence_completed_no_reply",
    },
    {
        "current_action": "setting_call",
        "trigger": "setting_call_completed",
        "outcome": "À closer",
        "next_action": "closing_call",
        "owner": "Closer",
        "due": "Date RDV ou maintenant",
        "conversation": "Ouverte",
        "required_support": "Mini note, qualification setter",
        "side_effects": "Lead passe en closing",
    },
    {
        "current_action": "setting_call",
        "trigger": "setting_call_not_reached",
        "outcome": "Prospect non joint",
        "next_action": "setting_call puis follow_up si rappels épuisés",
        "owner": "Setter I puis Setter II",
        "due": "+2h ouvrées, +24h ouvrées, puis +72h",
        "conversation": "Ouverte",
        "required_support": "Mini note d'appel",
        "side_effects": "Encoder tentative d'appel et compteur de rappel",
    },
    {
        "current_action": "setting_call",
        "trigger": "setting_call_completed_no_next_step",
        "outcome": "Prospect joint mais pas prêt ou pas de suite claire",
        "next_action": "follow_up",
        "owner": "Setter II",
        "due": "+72h après l'appel",
        "conversation": "Ouverte",
        "required_support": "Mini note",
        "side_effects": "Flux post_setting_undecided",
    },
    {
        "current_action": "setting_call",
        "trigger": "setting_call_terminal",
        "outcome": "Non pertinent ou Ne plus contacter",
        "next_action": "Aucune",
        "owner": "Personne",
        "due": "Aucun",
        "conversation": "Résolue",
        "required_support": "Mini note, qualification ou statut de contact",
        "side_effects": "Stopper relances",
    },
    {
        "current_action": "closing_call",
        "trigger": "closing_call_completed",
        "outcome": "Signé",
        "next_action": "Aucune",
        "owner": "Personne",
        "due": "Aucun",
        "conversation": "Résolue",
        "required_support": "Mini note, qualification closer signed",
        "side_effects": "Vente gagnée, stopper relances",
    },
    {
        "current_action": "closing_call",
        "trigger": "closing_call_completed",
        "outcome": "Va signer",
        "next_action": "follow_up",
        "owner": "Setter II",
        "due": "+72h puis flux closer_will_sign",
        "conversation": "Ouverte",
        "required_support": "Mini note, qualification closer will_sign",
        "side_effects": "Flux closer_will_sign",
    },
    {
        "current_action": "closing_call",
        "trigger": "closing_call_not_reached",
        "outcome": "Prospect non joint",
        "next_action": "closing_call puis follow_up si rappels épuisés",
        "owner": "Closer puis Setter II",
        "due": "+2h ouvrées, +24h ouvrées, puis +72h",
        "conversation": "Ouverte",
        "required_support": "Mini note d'appel",
        "side_effects": "Encoder tentative d'appel et compteur de rappel",
    },
    {
        "current_action": "closing_call",
        "trigger": "closing_call_completed_undecided",
        "outcome": "Prospect joint mais pas de décision claire",
        "next_action": "follow_up",
        "owner": "Setter II",
        "due": "+72h après l'appel",
        "conversation": "Ouverte",
        "required_support": "Mini note",
        "side_effects": "Flux post_closing_undecided",
    },
    {
        "current_action": "closing_call",
        "trigger": "closing_call_terminal",
        "outcome": "Non pertinent",
        "next_action": "Aucune",
        "owner": "Personne",
        "due": "Aucun",
        "conversation": "Résolue",
        "required_support": "Mini note, qualification closer not_relevant",
        "side_effects": "Stopper relances",
    },
    {
        "current_action": "follow_up lead-relative, sauf appel planifié",
        "trigger": "course_start_approaching",
        "outcome": "Lead non signé, date de cours connue",
        "next_action": "follow_up cours",
        "owner": "Setter II ou IA",
        "due": "J-14/J-7/J-3/J-1",
        "conversation": "Ouverte",
        "required_support": "Template cours",
        "side_effects": "Annuler la relance lead-relative concurrente ; ne pas remplacer un appel setting ou closing planifié",
    },
    {
        "current_action": "Toute action",
        "trigger": "terminal_status_applied",
        "outcome": "not_relevant, do_not_contact ou signed",
        "next_action": "Aucune",
        "owner": "Personne",
        "due": "Aucun",
        "conversation": "Résolue",
        "required_support": "Qualification ou statut de contact",
        "side_effects": "Stopper relances",
    },
    {
        "current_action": "Toute action",
        "trigger": "conversation_resolved",
        "outcome": "Utilisateur clôture avec motif obligatoire",
        "next_action": "Aucune",
        "owner": "Personne",
        "due": "Aucun",
        "conversation": "Résolue",
        "required_support": "Motif de résolution, note si motif l'exige",
        "side_effects": "Historiser résolution et fermer actions ouvertes",
    },
    {
        "current_action": "Aucune",
        "trigger": "conversation_reopened",
        "outcome": "Utilisateur rouvre",
        "next_action": "Action principale obligatoire",
        "owner": "Utilisateur courant ou responsable choisi",
        "due": "Maintenant ou planifié",
        "conversation": "Ouverte",
        "required_support": "Raison de réouverture",
        "side_effects": "Interdire conversation ouverte sans action",
    },
    {
        "current_action": "Toute action",
        "trigger": "business_hours_closed",
        "outcome": "Prospect écrit hors disponibilité",
        "next_action": "reply planifiée",
        "owner": "Backup ou prochain créneau",
        "due": "Prochain créneau ouvré",
        "conversation": "Ouverte",
        "required_support": "Option template hors horaire",
        "side_effects": "Message automatique possible",
    },
    {
        "current_action": "Toute action",
        "trigger": "assignee_unavailable",
        "outcome": "Responsable absent",
        "next_action": "Même action transférée",
        "owner": "Backup",
        "due": "Même échéance ou prochain créneau",
        "conversation": "Inchangée",
        "required_support": "Règle de backup",
        "side_effects": "Historiser transfert",
    },
]

PILOTAGE_VALIDATION_CASES = [
    {
        "statut": "Actif",
        "depart": "Aucune conversation Cockpit",
        "evenement": "SchoolDrive crée un Lead ou une Préinscription et le premier WhatsApp automatique est envoyé.",
        "reponse_systeme": "Le cockpit ouvre une conversation, stocke le snapshot SchoolDrive et programme le flux Lead sans réponse initiale.",
        "utilisateur": "Personne ne doit intervenir tant que le prospect ne répond pas ou que la relance n'arrive pas à échéance.",
        "resolution_action": "La relance initiale sera annulée si le prospect répond avant l'échéance.",
        "prochaine_action": "Relance Setter II à +72h après le WhatsApp automatique.",
    },
    {
        "statut": "Actif",
        "depart": "Lead ou Préinscription reçu de SchoolDrive",
        "evenement": "Le WhatsApp automatique est encore queued, absent ou non envoyé.",
        "reponse_systeme": "Le cockpit affiche la conversation et les messages SchoolDrive disponibles, mais ne crée pas encore de relance.",
        "utilisateur": "Aucune action commerciale automatique. Revue humaine seulement si la donnée paraît incohérente.",
        "resolution_action": "Quand SchoolDrive envoie un nouveau snapshot avec un WhatsApp sent, le cockpit recalcule la suite.",
        "prochaine_action": "Aucune relance tant que le premier WhatsApp n'est pas sent.",
    },
    {
        "statut": "Actif",
        "depart": "Flux Lead sans réponse initiale",
        "evenement": "Les 72h après le WhatsApp automatique sont écoulées et le prospect n'a pas répondu.",
        "reponse_systeme": "La relance devient à traiter pour Setter II.",
        "utilisateur": "Setter II relit la conversation, vérifie le template recommandé et envoie le modèle adapté.",
        "resolution_action": "L'envoi du template clôt l'action de relance.",
        "prochaine_action": "Étape suivante du même flux, ou clôture si c'était la dernière relance.",
    },
    {
        "statut": "Actif",
        "depart": "Toute conversation active avec relance future",
        "evenement": "Le prospect écrit un message WhatsApp entrant.",
        "reponse_systeme": "Les relances futures sont annulées et une action urgente Répondre au message est créée pour Setter I.",
        "utilisateur": "Setter I lit le message et répond, sauf si un statut de contact bloque l'envoi.",
        "resolution_action": "Le message envoyé clôt l'action Répondre.",
        "prochaine_action": "Relance Setter II à +72h si aucun appel n'est fixé, ou appel planifié si Setter I fixe un RDV.",
    },
    {
        "statut": "Actif",
        "depart": "Conversation avec appel setting ou closing déjà planifié",
        "evenement": "Le prospect écrit avant l'appel.",
        "reponse_systeme": "Le cockpit crée une action urgente Répondre au message sans annuler l'appel planifié.",
        "utilisateur": "Le responsable lit et répond au message. Il modifie l'appel seulement si le contenu du message l'exige.",
        "resolution_action": "La réponse clôt l'interruption Répondre.",
        "prochaine_action": "L'appel setting ou closing déjà planifié redevient la prochaine action visible.",
    },
    {
        "statut": "Actif",
        "depart": "Prospect marqué Ne plus contacter",
        "evenement": "Le prospect réécrit malgré le blocage.",
        "reponse_systeme": "Le cockpit crée une revue de contact pour Setter I et bloque tout envoi tant que le statut n'est pas levé.",
        "utilisateur": "Setter I lit le message et choisit Maintenir Ne plus contacter ou Lever et répondre.",
        "resolution_action": "Maintenir clôture la revue. Lever crée une action Répondre au message.",
        "prochaine_action": "Aucune si blocage maintenu ; Répondre maintenant si blocage levé.",
    },
    {
        "statut": "Actif",
        "depart": "Message entrant d'un numéro inconnu",
        "evenement": "Aucune fiche SchoolDrive/Cockpit ne correspond au numéro.",
        "reponse_systeme": "Le cockpit crée une fiche temporaire Inconnu(e), marquée À identifier, et une action Répondre.",
        "utilisateur": "L'équipe peut répondre, puis renseigne prénom, nom, cours et note temporaire dans Statuts.",
        "resolution_action": "La réponse suit les règles normales. L'identification reste à vérifier dans SchoolDrive.",
        "prochaine_action": "Répondre maintenant, puis relance Setter II ou appel selon le résultat.",
    },
    {
        "statut": "Actif",
        "depart": "Message entrant avec plusieurs fiches possibles",
        "evenement": "Plusieurs leads ou préinscriptions correspondent au même numéro.",
        "reponse_systeme": "Le cockpit crée une fiche temporaire À identifier pour éviter une mauvaise attribution.",
        "utilisateur": "L'équipe répond si nécessaire et documente l'identité probable sans fusion automatique.",
        "resolution_action": "La réponse clôt l'action Répondre. La fusion/identification définitive reste une dette V2.",
        "prochaine_action": "Suite commerciale normale sur la fiche temporaire jusqu'à résolution de l'identité.",
    },
    {
        "statut": "Actif",
        "depart": "Action Répondre ouverte",
        "evenement": "Setter I répond sans fixer de rendez-vous et sans appliquer de statut terminal.",
        "reponse_systeme": "Le cockpit clôt l'action Répondre et démarre le flux Conversation setter sans suite.",
        "utilisateur": "Setter I choisit la suite Pas de RDV avant l'envoi du message.",
        "resolution_action": "Le message WhatsApp sortant sert de preuve.",
        "prochaine_action": "Relance Setter II à +72h après le dernier message sortant.",
    },
    {
        "statut": "Actif",
        "depart": "Action Répondre ouverte",
        "evenement": "Setter I fixe un appel setting.",
        "reponse_systeme": "Le cockpit annule la relance de sécurité et crée une action Documenter appel setting.",
        "utilisateur": "Setter I choisit RDV setting fixé, responsable et date/heure.",
        "resolution_action": "Le message de confirmation clôt l'action Répondre.",
        "prochaine_action": "Documenter appel setting à la date/heure du rendez-vous.",
    },
    {
        "statut": "Actif",
        "depart": "Action Répondre ouverte",
        "evenement": "Setter I fixe directement un appel closing.",
        "reponse_systeme": "Le cockpit passe le parcours en closing et crée une action Documenter appel closing.",
        "utilisateur": "Setter I choisit RDV closing fixé, closer et date/heure.",
        "resolution_action": "Le message de confirmation clôt l'action Répondre.",
        "prochaine_action": "Documenter appel closing à la date/heure du rendez-vous.",
    },
    {
        "statut": "Actif",
        "depart": "Action Répondre ou appel en cours de traitement",
        "evenement": "L'utilisateur qualifie le prospect Non pertinent.",
        "reponse_systeme": "Le cockpit clôt la conversation et annule les actions ouvertes ou futures.",
        "utilisateur": "L'utilisateur choisit Non pertinent seulement si le prospect n'est pas un client potentiel.",
        "resolution_action": "La qualification terminale sert de preuve métier.",
        "prochaine_action": "Aucune.",
    },
    {
        "statut": "Actif",
        "depart": "Action Répondre ou appel en cours de traitement",
        "evenement": "Le prospect demande à ne plus être contacté.",
        "reponse_systeme": "Le cockpit applique Ne plus contacter, clôt la conversation et bloque les envois.",
        "utilisateur": "L'utilisateur sélectionne le statut de contact Ne plus contacter et ajoute une note si nécessaire.",
        "resolution_action": "Le statut de contact terminal sert de preuve.",
        "prochaine_action": "Aucune tant que le statut n'est pas levé.",
    },
    {
        "statut": "Actif",
        "depart": "Relance Setter II à traiter",
        "evenement": "La fenêtre WhatsApp est ouverte.",
        "reponse_systeme": "Le cockpit autorise le message libre ou le template.",
        "utilisateur": "Setter II choisit la réponse adaptée, idéalement le template recommandé si le flux le prévoit.",
        "resolution_action": "L'envoi clôt la relance.",
        "prochaine_action": "Étape suivante du flux si elle existe.",
    },
    {
        "statut": "Actif",
        "depart": "Relance Setter II à traiter",
        "evenement": "La fenêtre WhatsApp est fermée et un template approuvé est disponible.",
        "reponse_systeme": "Le cockpit bloque le message libre et pré-sélectionne le template recommandé quand il existe.",
        "utilisateur": "Setter II vérifie l'aperçu avec placeholders puis envoie le modèle approuvé.",
        "resolution_action": "L'envoi du template clôt la relance.",
        "prochaine_action": "Étape suivante du flux si elle existe.",
    },
    {
        "statut": "Actif",
        "depart": "Relance Setter II à traiter",
        "evenement": "La fenêtre WhatsApp est fermée et aucun template adapté n'existe.",
        "reponse_systeme": "La relance est bloquée et une demande de modèle peut être créée.",
        "utilisateur": "Setter II crée une demande de modèle avec le contexte nécessaire.",
        "resolution_action": "La demande bloque l'action jusqu'à disponibilité d'un template approuvé.",
        "prochaine_action": "Même relance, statut bloqué, puis réactivation quand un template est approuvé.",
    },
    {
        "statut": "Actif",
        "depart": "Demande de modèle ouverte",
        "evenement": "Un admin crée, soumet ou synchronise le template approuvé.",
        "reponse_systeme": "Le cockpit lie le template à la demande et rend la relance exécutable quand le statut est approuvé.",
        "utilisateur": "L'admin traite la demande dans Modèles ou Admin. Setter II reprend ensuite la relance.",
        "resolution_action": "Le statut de la demande passe à soumis, approuvé, rejeté ou annulé.",
        "prochaine_action": "Relance Setter II débloquée si le template est approuvé.",
    },
    {
        "statut": "Actif",
        "depart": "Flux de relance en cours",
        "evenement": "Une relance intermédiaire est envoyée.",
        "reponse_systeme": "Le cockpit avance au prochain événement du flux en gardant l'ancre du flux.",
        "utilisateur": "Setter II vérifie que l'étape suivante est cohérente.",
        "resolution_action": "Le message sortant clôt l'étape courante.",
        "prochaine_action": "Prochaine relance du même flux, à la date prévue.",
    },
    {
        "statut": "Actif",
        "depart": "Dernière étape d'un flux de relance",
        "evenement": "La dernière relance est envoyée et le prospect ne répond pas.",
        "reponse_systeme": "Le cockpit ne crée plus de suite et clôt la conversation.",
        "utilisateur": "Aucune action supplémentaire sauf si le prospect réécrit.",
        "resolution_action": "La dernière relance clôt le flux.",
        "prochaine_action": "Aucune, conversation terminée avec motif suivi terminé sans réponse.",
    },
    {
        "statut": "Actif",
        "depart": "Lead ou Préinscription non signé avec date de cours connue",
        "evenement": "Une relance liée au début du cours tombe dans les 24h d'une relance lead/préinscription.",
        "reponse_systeme": "La relance cours gagne, la relance lead/préinscription concurrente est annulée.",
        "utilisateur": "Setter II suit la relance cours.",
        "resolution_action": "L'envoi de la relance cours clôt cette action.",
        "prochaine_action": "Étape suivante du flux Début de cours ou clôture selon le flux.",
    },
    {
        "statut": "Actif",
        "depart": "Appel setting ou closing déjà planifié",
        "evenement": "Une relance liée au début du cours devient éligible.",
        "reponse_systeme": "Le cockpit ne remplace pas l'appel planifié.",
        "utilisateur": "Le responsable conserve l'appel et documente l'appel au moment prévu.",
        "resolution_action": "L'appel reste l'action principale.",
        "prochaine_action": "Documenter l'appel planifié.",
    },
    {
        "statut": "Actif",
        "depart": "Catégorie de cours active sans date SchoolDrive explicite",
        "evenement": "Un Lead arrive avec seulement une catégorie de cours.",
        "reponse_systeme": "Le cockpit utilise la session de référence configurée dans Pilotage pour calculer les flux cours.",
        "utilisateur": "L'admin doit maintenir les sessions de référence à jour.",
        "resolution_action": "Aucune action utilisateur immédiate si la session est configurée.",
        "prochaine_action": "Flux normal lead/préinscription et flux Début de cours selon la date de référence.",
    },
    {
        "statut": "Actif",
        "depart": "Catégorie de cours active",
        "evenement": "La session de référence est déjà passée.",
        "reponse_systeme": "Le cockpit ne lance pas le flux Début de cours sur cette session.",
        "utilisateur": "L'admin configure la prochaine session de référence.",
        "resolution_action": "La correction de session ne recalcule pas les actions déjà ouvertes en V1.",
        "prochaine_action": "Nouveaux flux seulement après correction, recalcul contrôlé prévu en V2.",
    },
    {
        "statut": "Actif",
        "depart": "Catégorie de cours non activée dans Pilotage",
        "evenement": "SchoolDrive envoie un lead ou une préinscription pour cette catégorie.",
        "reponse_systeme": "Le cockpit stocke la conversation mais ne démarre pas le flux structuré Setter II.",
        "utilisateur": "Setter I reçoit une revue humaine. L'admin peut activer la catégorie plus tard.",
        "resolution_action": "La revue humaine doit décider de la prochaine action.",
        "prochaine_action": "Répondre, relancer, appeler ou attendre selon décision humaine.",
    },
    {
        "statut": "Actif",
        "depart": "Appel setting planifié",
        "evenement": "Le moment de l'appel arrive.",
        "reponse_systeme": "L'action apparaît à traiter pour Setter I.",
        "utilisateur": "Setter I appelle puis documente le résultat avec une mini-note obligatoire.",
        "resolution_action": "La documentation de l'appel clôt l'action.",
        "prochaine_action": "Closing, rappel d'appel, relance Setter II, clôture ou blocage selon résultat.",
    },
    {
        "statut": "Actif",
        "depart": "Appel setting à documenter",
        "evenement": "L'appel est réussi et le prospect doit passer au closing.",
        "reponse_systeme": "Le cockpit crée une action Documenter appel closing et passe le parcours en closing.",
        "utilisateur": "Setter I choisit Passer au closing, closer, date/heure et note.",
        "resolution_action": "La note d'appel apparaît dans la conversation comme note interne.",
        "prochaine_action": "Documenter appel closing pour le closer.",
    },
    {
        "statut": "Actif",
        "depart": "Appel setting à documenter",
        "evenement": "Le prospect n'est pas joint.",
        "reponse_systeme": "Le cockpit crée un rappel d'appel +2h ouvrées, puis +24h ouvrées, puis une relance Setter II.",
        "utilisateur": "Setter I documente la tentative avec une mini-note.",
        "resolution_action": "Chaque tentative clôt l'action d'appel courante.",
        "prochaine_action": "Rappel d'appel setting, puis relance Setter II si les rappels sont épuisés.",
    },
    {
        "statut": "Actif",
        "depart": "Appel setting à documenter",
        "evenement": "Le prospect est joint mais aucune suite claire n'est obtenue.",
        "reponse_systeme": "Le cockpit lance une relance Setter II à +72h.",
        "utilisateur": "Setter I documente ce qui s'est dit.",
        "resolution_action": "La mini-note clôt l'appel.",
        "prochaine_action": "Relance Setter II à +72h.",
    },
    {
        "statut": "Actif",
        "depart": "Appel setting à documenter",
        "evenement": "Le prospect est non pertinent ou demande à ne plus être contacté.",
        "reponse_systeme": "Le cockpit clôt la conversation et annule toutes les actions futures.",
        "utilisateur": "Setter I choisit le résultat terminal et documente la raison.",
        "resolution_action": "La mini-note et le statut terminal clôturent l'appel.",
        "prochaine_action": "Aucune.",
    },
    {
        "statut": "Actif",
        "depart": "Appel closing planifié",
        "evenement": "Le moment de l'appel arrive.",
        "reponse_systeme": "L'action apparaît à traiter pour le closer.",
        "utilisateur": "Le closer appelle puis documente le résultat avec une mini-note obligatoire.",
        "resolution_action": "La documentation de l'appel clôt l'action.",
        "prochaine_action": "Aucune, relance Setter II ou rappel d'appel selon résultat.",
    },
    {
        "statut": "Actif",
        "depart": "Appel closing à documenter",
        "evenement": "Le prospect signe.",
        "reponse_systeme": "Le cockpit marque la vente comme gagnée, clôt la conversation et annule les relances.",
        "utilisateur": "Le closer choisit A signé et ajoute la note.",
        "resolution_action": "La mini-note d'appel clôt l'action.",
        "prochaine_action": "Aucune.",
    },
    {
        "statut": "Actif",
        "depart": "Appel closing à documenter",
        "evenement": "Le closer estime que le prospect va signer.",
        "reponse_systeme": "Le cockpit lance le flux Va signer.",
        "utilisateur": "Le closer choisit Va signer et documente le contexte.",
        "resolution_action": "La mini-note clôt l'appel.",
        "prochaine_action": "Relance Setter II à +72h, puis étapes du flux Va signer.",
    },
    {
        "statut": "Actif",
        "depart": "Appel closing à documenter",
        "evenement": "Le prospect n'est pas joint.",
        "reponse_systeme": "Le cockpit crée un rappel d'appel +2h ouvrées, puis +24h ouvrées, puis une relance Setter II.",
        "utilisateur": "Le closer documente la tentative avec une mini-note.",
        "resolution_action": "Chaque tentative clôt l'action d'appel courante.",
        "prochaine_action": "Rappel d'appel closing, puis relance Setter II si les rappels sont épuisés.",
    },
    {
        "statut": "Actif",
        "depart": "Appel closing à documenter",
        "evenement": "Le prospect est joint mais aucune décision claire n'est obtenue.",
        "reponse_systeme": "Le cockpit lance le flux Post-appel closing indécis.",
        "utilisateur": "Le closer documente l'échange et choisit Indécis.",
        "resolution_action": "La mini-note clôt l'appel.",
        "prochaine_action": "Relance Setter II à +72h.",
    },
    {
        "statut": "Actif",
        "depart": "Appel closing à documenter",
        "evenement": "Le prospect est non pertinent.",
        "reponse_systeme": "Le cockpit clôt la conversation et annule toutes les actions futures.",
        "utilisateur": "Le closer choisit Non pertinent et documente la raison.",
        "resolution_action": "La mini-note et la qualification terminale clôturent l'appel.",
        "prochaine_action": "Aucune.",
    },
    {
        "statut": "Actif",
        "depart": "Conversation active",
        "evenement": "Un utilisateur clôt manuellement la conversation.",
        "reponse_systeme": "Le cockpit exige une note/motif, ferme les actions ouvertes et passe la conversation en terminée.",
        "utilisateur": "L'utilisateur ne doit clore que s'il n'y a réellement plus rien à faire.",
        "resolution_action": "La note de clôture apparaît comme note interne.",
        "prochaine_action": "Aucune.",
    },
    {
        "statut": "Actif",
        "depart": "Conversation terminée",
        "evenement": "Un utilisateur réactive la conversation.",
        "reponse_systeme": "Le cockpit exige une note et une prochaine action principale.",
        "utilisateur": "L'utilisateur choisit répondre, relancer, appel setting ou appel closing.",
        "resolution_action": "La note de réactivation apparaît comme note interne.",
        "prochaine_action": "Action choisie, maintenant ou planifiée.",
    },
    {
        "statut": "Actif",
        "depart": "SchoolDrive record existant dans le cockpit",
        "evenement": "SchoolDrive envoie un snapshot archivé.",
        "reponse_systeme": "Le cockpit met à jour le record, clôt la conversation et ferme les actions ouvertes.",
        "utilisateur": "Aucune action sauf revue si l'archivage semble incorrect.",
        "resolution_action": "L'événement SchoolDrive sert de preuve.",
        "prochaine_action": "Aucune.",
    },
    {
        "statut": "Actif",
        "depart": "Webhook SchoolDrive",
        "evenement": "Snapshot duplicate ou plus ancien que le snapshot déjà accepté.",
        "reponse_systeme": "Le cockpit retourne OK mais ignore l'événement pour éviter de réécrire l'état avec une donnée ancienne.",
        "utilisateur": "Aucune action.",
        "resolution_action": "L'événement est journalisé comme duplicate ou stale.",
        "prochaine_action": "Aucune modification de la conversation.",
    },
    {
        "statut": "Partiel / à valider",
        "depart": "Prospect écrit hors horaires",
        "evenement": "Message entrant en dehors des horaires entreprise ou utilisateur.",
        "reponse_systeme": "Règle cible : créer la réponse au prochain créneau ouvré et envoyer éventuellement un accusé de réception.",
        "utilisateur": "À valider avant automatisation : texte d'accusé, horaires, cas de week-end et jours fériés.",
        "resolution_action": "V1 conserve la logique de réponse humaine ; l'automatisation complète est à confirmer.",
        "prochaine_action": "Réponse Setter I au prochain créneau ou selon backup configuré.",
    },
    {
        "statut": "V2 / à valider",
        "depart": "Action attribuée à une personne absente",
        "evenement": "Le responsable est indisponible.",
        "reponse_systeme": "Règle cible : transférer au backup configuré sans changer la nature de l'action.",
        "utilisateur": "L'admin doit maintenir horaires, absences et backups.",
        "resolution_action": "Le transfert doit être journalisé.",
        "prochaine_action": "Même action, nouveau responsable ou attente si aucun backup.",
    },
]

LEAD_TYPES = [
    {
        "type": "lead",
        "label": "Lead",
        "source": "Demande d'information sans session pré-sélectionnée, généralement paid ads.",
        "course_date_rule": "Utiliser la prochaine session pertinente depuis SchoolDrive, à confirmer.",
    },
    {
        "type": "presubscription",
        "label": "Préinscription",
        "source": "Le prospect a pré-sélectionné une session, généralement via recherche naturelle.",
        "course_date_rule": "Utiliser la date de cette session SchoolDrive.",
    },
]

DEMO_TEMPLATE_CATALOG = [
    {
        "name": "demo_initial_offer",
        "category": "marketing",
        "body": "Bonjour {{first_name}}, merci pour votre demande concernant {{course_title}}. Nous avons actuellement une offre spéciale. Répondez à ce message et je vous donne les détails. Yasmine",
        "sequence": "lead_created",
    },
    {
        "name": "demo_relance_72h_1",
        "category": "marketing",
        "body": "Bonjour {{first_name}}, je me permets de revenir vers vous au sujet de {{course_title}}. Souhaitez-vous recevoir les informations pratiques ? Yasmine",
        "sequence": "lead_no_reply",
    },
    {
        "name": "demo_relance_72h_2",
        "category": "marketing",
        "body": "Bonjour {{first_name}}, avez-vous encore un intérêt pour la formation {{course_title}} ? Je peux vous orienter rapidement. Yasmine",
        "sequence": "lead_no_reply",
    },
    {
        "name": "demo_relance_72h_3",
        "category": "marketing",
        "body": "Bonjour {{first_name}}, je vous relance une dernière fois cette semaine pour {{course_title}}. Souhaitez-vous que l'on vous appelle ? Yasmine",
        "sequence": "lead_no_reply",
    },
    {
        "name": "demo_relance_7j_1",
        "category": "marketing",
        "body": "Bonjour {{first_name}}, les inscriptions avancent pour {{course_title}}. Voulez-vous que je vérifie les possibilités pour vous ? Yasmine",
        "sequence": "lead_no_reply",
    },
    {
        "name": "demo_relance_7j_2",
        "category": "marketing",
        "body": "Bonjour {{first_name}}, je reviens vers vous concernant votre demande ESSR. Souhaitez-vous toujours des informations ? Yasmine",
        "sequence": "lead_no_reply",
    },
    {
        "name": "demo_relance_30j_stop",
        "category": "marketing",
        "body": "Bonjour {{first_name}}, je clôture votre demande pour le moment. Si vous souhaitez reprendre le sujet, répondez simplement à ce message. Yasmine",
        "sequence": "lead_no_reply",
    },
    {
        "name": "demo_relance_setting_72h_1",
        "category": "utility",
        "body": "Bonjour {{first_name}}, je reviens vers vous après notre échange concernant {{course_title}}. Souhaitez-vous que l'on fixe un moment ? Yasmine",
        "sequence": "setter_no_next_step",
    },
    {
        "name": "demo_relance_setting_72h_2",
        "category": "utility",
        "body": "Bonjour {{first_name}}, avez-vous pu réfléchir à la suite pour {{course_title}} ? Je peux vous aider à avancer. Yasmine",
        "sequence": "setter_no_next_step",
    },
    {
        "name": "demo_relance_setting_72h_3",
        "category": "utility",
        "body": "Bonjour {{first_name}}, je vous relance concernant notre échange sur {{course_title}}. Souhaitez-vous être rappelé ? Yasmine",
        "sequence": "setter_no_next_step",
    },
    {
        "name": "demo_relance_setting_7j_1",
        "category": "utility",
        "body": "Bonjour {{first_name}}, je reviens vers vous une semaine après notre échange. Souhaitez-vous reprendre le sujet ? Yasmine",
        "sequence": "setter_no_next_step",
    },
    {
        "name": "demo_relance_setting_7j_2",
        "category": "utility",
        "body": "Bonjour {{first_name}}, souhaitez-vous encore que l'on vous accompagne pour {{course_title}} ? Yasmine",
        "sequence": "setter_no_next_step",
    },
    {
        "name": "demo_relance_setting_30j_stop",
        "category": "utility",
        "body": "Bonjour {{first_name}}, je clôture le suivi pour le moment. Vous pouvez me répondre si vous souhaitez reprendre. Yasmine",
        "sequence": "setter_no_next_step",
    },
    {
        "name": "demo_setting_rdv",
        "category": "utility",
        "body": "Bonjour {{first_name}}, êtes-vous disponible demain pour un court appel ? Mon collègue pourra vous présenter la formation {{course_title}}. Yasmine",
        "sequence": "setter_conversation",
    },
    {
        "name": "demo_va_signer_72h_1",
        "category": "utility",
        "body": "Bonjour {{first_name}}, je reviens vers vous pour finaliser votre inscription à {{course_title}}. Avez-vous besoin d'aide pour la dernière étape ? Yasmine",
        "sequence": "closer_will_sign",
    },
    {
        "name": "demo_va_signer_72h_2",
        "category": "utility",
        "body": "Bonjour {{first_name}}, je voulais vérifier si tout est bon pour finaliser votre inscription à {{course_title}}. Yasmine",
        "sequence": "closer_will_sign",
    },
    {
        "name": "demo_va_signer_72h_3",
        "category": "utility",
        "body": "Bonjour {{first_name}}, souhaitez-vous que je vous aide à terminer votre inscription aujourd'hui ? Yasmine",
        "sequence": "closer_will_sign",
    },
    {
        "name": "demo_va_signer_7j_1",
        "category": "utility",
        "body": "Bonjour {{first_name}}, je reviens vers vous concernant la finalisation de {{course_title}}. Yasmine",
        "sequence": "closer_will_sign",
    },
    {
        "name": "demo_va_signer_7j_2",
        "category": "utility",
        "body": "Bonjour {{first_name}}, dois-je garder votre dossier ouvert pour {{course_title}} ? Yasmine",
        "sequence": "closer_will_sign",
    },
    {
        "name": "demo_va_signer_30j_stop",
        "category": "utility",
        "body": "Bonjour {{first_name}}, sans retour de votre part je clôture le suivi. Répondez-moi si vous souhaitez reprendre. Yasmine",
        "sequence": "closer_will_sign",
    },
    {
        "name": "demo_cours_j14",
        "category": "marketing",
        "body": "Bonjour {{first_name}}, la session {{course_title}} démarre dans deux semaines. Souhaitez-vous que je vérifie les possibilités pour vous ? Yasmine",
        "sequence": "course_start",
    },
    {
        "name": "demo_cours_j7",
        "category": "marketing",
        "body": "Bonjour {{first_name}}, la session {{course_title}} commence bientôt. Souhaitez-vous encore recevoir les informations ? Yasmine",
        "sequence": "course_start",
    },
    {
        "name": "demo_cours_j3",
        "category": "marketing",
        "body": "Bonjour {{first_name}}, la session {{course_title}} commence bientôt. Souhaitez-vous que je vérifie s'il reste une possibilité pour vous ? Yasmine",
        "sequence": "course_start",
    },
    {
        "name": "demo_cours_j1",
        "category": "marketing",
        "body": "Bonjour {{first_name}}, la session {{course_title}} commence demain. Souhaitez-vous un dernier point rapide ? Yasmine",
        "sequence": "course_start",
    },
    {
        "name": "demo_hors_horaire",
        "category": "utility",
        "body": "Bonjour {{first_name}}, merci pour votre message. L'équipe est actuellement indisponible, nous vous répondrons au prochain créneau ouvré. Yasmine",
        "sequence": "out_of_hours",
    },
]
