from __future__ import annotations


SOURCE_TYPES = [
    {
        "value": "paid_ads",
        "label": "Paid ads",
        "meaning": "Le prospect vient d'une campagne payante, par exemple Google Ads, Meta Ads ou Bing Ads.",
    },
    {
        "value": "organic",
        "label": "Recherche naturelle",
        "meaning": "Le prospect vient d'une recherche naturelle et arrive généralement comme préinscription.",
    },
    {
        "value": "mock",
        "label": "Mock local",
        "meaning": "Donnée de démonstration locale.",
    },
    {
        "value": "unknown",
        "label": "Inconnu",
        "meaning": "Origine non encore synchronisée.",
    },
]

QUALIFICATION_STATUSES = [
    {
        "value": "neutral",
        "label": "Neutre",
        "meaning": "Qualification par défaut, le prospect n'a pas encore été jugé.",
        "stops_followups": False,
    },
    {
        "value": "eligible",
        "label": "Éligible",
        "meaning": "Le prospect peut continuer dans le parcours commercial.",
        "stops_followups": False,
    },
    {
        "value": "not_relevant",
        "label": "Non pertinent",
        "meaning": "Le prospect ne correspond pas à une opportunité commerciale utile.",
        "stops_followups": True,
    },
    {
        "value": "will_sign",
        "label": "Va signer",
        "meaning": "Le closer estime que le prospect va signer, relance dédiée à activer.",
        "stops_followups": False,
    },
    {
        "value": "signed",
        "label": "A signé",
        "meaning": "La vente est gagnée, les relances commerciales s'arrêtent.",
        "stops_followups": True,
    },
]

CONTACT_STATUSES = [
    {
        "value": "contact_allowed",
        "label": "Contact autorisé",
        "meaning": "Le prospect peut être contacté dans le respect des règles WhatsApp.",
        "stops_followups": False,
    },
    {
        "value": "do_not_contact",
        "label": "Ne plus contacter",
        "meaning": "Le prospect a demandé à ne plus être contacté. Aucune relance automatique ne doit être créée.",
        "stops_followups": True,
    },
]

STOP_QUALIFICATION_STATUSES = {
    item["value"] for item in QUALIFICATION_STATUSES if item["stops_followups"]
}
STOP_CONTACT_STATUSES = {
    item["value"] for item in CONTACT_STATUSES if item["stops_followups"]
}
STOP_FOLLOWUP_STATUSES = STOP_QUALIFICATION_STATUSES | STOP_CONTACT_STATUSES

RESOLUTION_REASONS = [
    {
        "value": "signed",
        "label": "Signé",
        "meaning": "Le prospect a signé. La vente est gagnée.",
        "requires_note": False,
    },
    {
        "value": "not_relevant",
        "label": "Non pertinent",
        "meaning": "Le prospect n'est pas une opportunité commerciale utile.",
        "requires_note": False,
    },
    {
        "value": "do_not_contact",
        "label": "Ne plus contacter",
        "meaning": "Le prospect a demandé à ne plus être contacté.",
        "requires_note": True,
    },
    {
        "value": "duplicate",
        "label": "Doublon",
        "meaning": "La demande existe déjà ailleurs.",
        "requires_note": False,
    },
    {
        "value": "handled_elsewhere",
        "label": "Traité ailleurs",
        "meaning": "Le dossier est traité hors de cette conversation.",
        "requires_note": True,
    },
    {
        "value": "sequence_completed_no_reply",
        "label": "Séquence terminée sans réponse",
        "meaning": "La dernière relance prévue a été envoyée et le prospect n'a pas répondu.",
        "requires_note": False,
    },
    {
        "value": "error",
        "label": "Erreur",
        "meaning": "La conversation ou le lead a été créé par erreur.",
        "requires_note": True,
    },
    {
        "value": "other",
        "label": "Autre",
        "meaning": "Cas non couvert par les motifs standard.",
        "requires_note": True,
    },
]

TEMPLATE_REQUEST_STATUSES = [
    {"value": "to_create", "label": "À créer"},
    {"value": "submitted", "label": "Soumis"},
    {"value": "approved", "label": "Approuvé"},
    {"value": "rejected", "label": "Rejeté"},
    {"value": "cancelled", "label": "Annulé"},
]

SALES_ACTORS = [
    {
        "code": "setter_1",
        "label": "Setter 1",
        "person": "Mihary",
        "email": "service.etudiants@essr.ch",
        "responsibility": "Conversation écrite active, revue des messages entrants et entretien de setting.",
        "automation": "Humain en V1",
    },
    {
        "code": "setter_2",
        "label": "Setter 2",
        "person": "Setter 2",
        "email": "setter2@essr.ch",
        "responsibility": "Relances structurées par template, hors conversation active.",
        "automation": "Candidat prioritaire à l'automatisation après V1",
    },
    {
        "code": "closer",
        "label": "Closer",
        "person": "Yasmine",
        "email": "yasmine@essr.ch",
        "responsibility": "Closing téléphonique et qualification de closing.",
        "automation": "Humain",
    },
]

OPERATING_RULES = [
    {
        "rule": "Origine formulaire",
        "value": "Le prospect remplit un formulaire web. SchoolDrive crée ensuite le Lead ou la Préinscription.",
        "effect": "Le cockpit reçoit le lead depuis SchoolDrive et ne remplace pas SchoolDrive comme source de vérité.",
    },
    {
        "rule": "Lead vs Préinscription",
        "value": "Les Leads viennent principalement des paid ads. Les Préinscriptions viennent principalement du trafic organique.",
        "effect": "Le type SchoolDrive influence l'affichage cours/catégorie et les rappels liés au début de session.",
    },
    {
        "rule": "Fenêtre WhatsApp",
        "value": "Ouverte 24h après chaque message entrant du prospect.",
        "effect": "Message libre possible uniquement pendant cette fenêtre.",
    },
    {
        "rule": "Premier template automatique",
        "value": "Envoyé par SchoolDrive/Twilio à la création du lead.",
        "effect": "N'ouvre pas la fenêtre WhatsApp tant que le prospect ne répond pas.",
    },
    {
        "rule": "Relances hors fenêtre",
        "value": "Template approuvé obligatoire.",
        "effect": "Setter 2 relit la conversation, choisit le template approprié ou demande un nouveau template.",
    },
    {
        "rule": "Délai minimum WhatsApp",
        "value": "24h entre deux relances sortantes.",
        "effect": "Une relance concurrente trop proche doit être annulée ou repoussée.",
    },
    {
        "rule": "Conflit lead vs cours",
        "value": "La relance liée à une date de cours gagne toujours.",
        "effect": "La relance liée au cycle du lead est annulée.",
    },
    {
        "rule": "Non pertinent",
        "value": "Qualification commerciale négative.",
        "effect": "Fin du process et arrêt des relances.",
    },
    {
        "rule": "Ne plus contacter",
        "value": "Statut de contact séparé de la qualification commerciale.",
        "effect": "Blocage strict des relances. Si le prospect réécrit, une revue Setter 1 est créée.",
    },
    {
        "rule": "Automatisation V1",
        "value": "Le cockpit crée les tâches de relance mais n'envoie pas automatiquement les templates.",
        "effect": "L'automatisation des relances et du Setter 2 est gardée pour V2.",
    },
]

SCHEDULE_RULES = [
    {
        "rule": "Horaires humains",
        "value": "À confirmer par collaborateur.",
        "effect": "Hors horaire, créer une action différée ou envoyer un répondeur automatique.",
    },
    {
        "rule": "Absence",
        "value": "À confirmer par collaborateur.",
        "effect": "Transfert de la prochaine action à un backup défini.",
    },
    {
        "rule": "Répondeur hors horaire",
        "value": "Template ou message automatique à définir.",
        "effect": "Informer le prospect qu'un retour sera fait au prochain créneau ouvré.",
    },
]

ASSIGNMENT_RULES = [
    {
        "trigger": "message entrant standard",
        "owner": "Setter 1",
        "effect": "Le prospect passe en haut de la file de Mihary avec une action Répondre.",
    },
    {
        "trigger": "message entrant d'un prospect Ne plus contacter",
        "owner": "Setter 1",
        "effect": "Créer une revue de statut de contact. Aucune relance automatique.",
    },
    {
        "trigger": "relance structurée",
        "owner": "Setter 2",
        "effect": "Relire la conversation, choisir le template et envoyer manuellement en V1.",
    },
    {
        "trigger": "passage au closing",
        "owner": "Closer",
        "effect": "Créer une action Appel de closing pour Yasmine.",
    },
    {
        "trigger": "responsable absent",
        "owner": "Backup configuré",
        "effect": "Transférer l'action sans changer sa nature ni son historique.",
    },
]

SEQUENCES = [
    {
        "code": "lead_no_reply",
        "label": "Lead sans réponse initiale",
        "timeline": "Relative au message automatique initial",
        "trigger": "Template automatique envoyé, aucun message entrant du prospect.",
        "owner": "Setter 2",
        "stop_when": "Réponse entrante, non pertinent, ne plus contacter, signé.",
    },
    {
        "code": "setter_no_next_step",
        "label": "Conversation setter sans suite",
        "timeline": "Relative au dernier message sortant ou échange setter",
        "trigger": "Setter 1 a échangé, aucun RDV posé et 72h sans échange.",
        "owner": "Setter 2",
        "stop_when": "Réponse entrante, RDV posé, non pertinent, ne plus contacter.",
    },
    {
        "code": "setting_call_not_reached",
        "label": "Appel setting non joint",
        "timeline": "Relative à la tentative d'appel setting",
        "trigger": "Setter 1 n'a pas pu joindre le prospect.",
        "owner": "Setter 1 puis Setter 2",
        "stop_when": "Prospect joint, réponse entrante, non pertinent, ne plus contacter.",
    },
    {
        "code": "closing_call_not_reached",
        "label": "Appel closing non joint",
        "timeline": "Relative à la tentative d'appel closing",
        "trigger": "Closer n'a pas pu joindre le prospect.",
        "owner": "Closer puis Setter 2",
        "stop_when": "Prospect joint, réponse entrante, signé, non pertinent, ne plus contacter.",
    },
    {
        "code": "post_call_undecided",
        "label": "Post-appel sans décision claire",
        "timeline": "Relative à l'appel terminé",
        "trigger": "Le prospect a été joint mais aucune décision claire n'est prise.",
        "owner": "Setter 2",
        "stop_when": "Réponse entrante, RDV posé, signature, non pertinent, ne plus contacter.",
    },
    {
        "code": "closer_will_sign",
        "label": "Closer : va signer",
        "timeline": "Relative à la qualification closer",
        "trigger": "Yasmine qualifie le prospect en Va signer.",
        "owner": "Setter 2",
        "stop_when": "Signature, réponse entrante nécessitant humain, ne plus contacter.",
    },
    {
        "code": "course_start",
        "label": "Début de cours",
        "timeline": "Relative au cours",
        "trigger": "Date de début de session connue dans SchoolDrive.",
        "owner": "Setter 2 ou automatisation",
        "stop_when": "Signature, non pertinent, ne plus contacter.",
    },
]

SEQUENCE_STEPS = [
    {
        "sequence_code": "lead_no_reply",
        "step_index": 1,
        "delay": "+72h",
        "template_name": "demo_relance_72h_1",
        "meaning": "Première relance après le message automatique initial.",
    },
    {
        "sequence_code": "lead_no_reply",
        "step_index": 2,
        "delay": "+72h",
        "template_name": "demo_relance_72h_2",
        "meaning": "Deuxième relance 72h après la relance précédente.",
    },
    {
        "sequence_code": "lead_no_reply",
        "step_index": 3,
        "delay": "+72h",
        "template_name": "demo_relance_72h_3",
        "meaning": "Troisième relance 72h après la relance précédente.",
    },
    {
        "sequence_code": "lead_no_reply",
        "step_index": 4,
        "delay": "+7j",
        "template_name": "demo_relance_7j_1",
        "meaning": "Relance espacée une semaine après la troisième relance.",
    },
    {
        "sequence_code": "lead_no_reply",
        "step_index": 5,
        "delay": "+7j",
        "template_name": "demo_relance_7j_2",
        "meaning": "Dernière relance courte une semaine après la précédente.",
    },
    {
        "sequence_code": "lead_no_reply",
        "step_index": 6,
        "delay": "+30j",
        "template_name": "demo_relance_30j_stop",
        "meaning": "Relance finale avant résolution sans réponse.",
    },
    {
        "sequence_code": "setter_no_next_step",
        "step_index": 1,
        "delay": "+72h",
        "template_name": "demo_relance_setting_72h_1",
        "meaning": "Relance après échange setter sans rendez-vous.",
    },
    {
        "sequence_code": "setter_no_next_step",
        "step_index": 2,
        "delay": "+72h",
        "template_name": "demo_relance_setting_72h_2",
        "meaning": "Deuxième relance après échange setter sans rendez-vous.",
    },
    {
        "sequence_code": "setter_no_next_step",
        "step_index": 3,
        "delay": "+72h",
        "template_name": "demo_relance_setting_72h_3",
        "meaning": "Troisième relance après échange setter sans rendez-vous.",
    },
    {
        "sequence_code": "setter_no_next_step",
        "step_index": 4,
        "delay": "+7j",
        "template_name": "demo_relance_setting_7j_1",
        "meaning": "Relance espacée une semaine.",
    },
    {
        "sequence_code": "setter_no_next_step",
        "step_index": 5,
        "delay": "+7j",
        "template_name": "demo_relance_setting_7j_2",
        "meaning": "Dernière relance courte avant relance finale.",
    },
    {
        "sequence_code": "setter_no_next_step",
        "step_index": 6,
        "delay": "+30j",
        "template_name": "demo_relance_setting_30j_stop",
        "meaning": "Relance finale avant résolution sans réponse.",
    },
    {
        "sequence_code": "setting_call_not_reached",
        "step_index": 1,
        "delay": "+2h ouvrées",
        "template_name": "",
        "meaning": "Premier rappel téléphonique après appel setting non joint.",
    },
    {
        "sequence_code": "setting_call_not_reached",
        "step_index": 2,
        "delay": "+24h ouvrées",
        "template_name": "",
        "meaning": "Deuxième rappel téléphonique après appel setting non joint.",
    },
    {
        "sequence_code": "setting_call_not_reached",
        "step_index": 3,
        "delay": "+72h",
        "template_name": "demo_relance_setting_72h_1",
        "meaning": "Passage à Setter 2 pour relance WhatsApp.",
    },
    {
        "sequence_code": "closing_call_not_reached",
        "step_index": 1,
        "delay": "+2h ouvrées",
        "template_name": "",
        "meaning": "Premier rappel téléphonique après closing non joint.",
    },
    {
        "sequence_code": "closing_call_not_reached",
        "step_index": 2,
        "delay": "+24h ouvrées",
        "template_name": "",
        "meaning": "Deuxième rappel téléphonique après closing non joint.",
    },
    {
        "sequence_code": "closing_call_not_reached",
        "step_index": 3,
        "delay": "+72h",
        "template_name": "demo_va_signer_72h_1",
        "meaning": "Passage à Setter 2 pour relance WhatsApp.",
    },
    {
        "sequence_code": "post_call_undecided",
        "step_index": 1,
        "delay": "+72h",
        "template_name": "demo_relance_72h_1",
        "meaning": "Relance après appel où le prospect a été joint mais reste indécis.",
    },
    {
        "sequence_code": "closer_will_sign",
        "step_index": 1,
        "delay": "+72h",
        "template_name": "demo_va_signer_72h_1",
        "meaning": "Première relance après qualification closer Va signer.",
    },
    {
        "sequence_code": "closer_will_sign",
        "step_index": 2,
        "delay": "+72h",
        "template_name": "demo_va_signer_72h_2",
        "meaning": "Deuxième relance Va signer.",
    },
    {
        "sequence_code": "closer_will_sign",
        "step_index": 3,
        "delay": "+72h",
        "template_name": "demo_va_signer_72h_3",
        "meaning": "Troisième relance Va signer.",
    },
    {
        "sequence_code": "closer_will_sign",
        "step_index": 4,
        "delay": "+7j",
        "template_name": "demo_va_signer_7j_1",
        "meaning": "Relance espacée une semaine pour finaliser.",
    },
    {
        "sequence_code": "closer_will_sign",
        "step_index": 5,
        "delay": "+7j",
        "template_name": "demo_va_signer_7j_2",
        "meaning": "Dernière relance courte pour finaliser.",
    },
    {
        "sequence_code": "closer_will_sign",
        "step_index": 6,
        "delay": "+30j",
        "template_name": "demo_va_signer_30j_stop",
        "meaning": "Relance finale Va signer avant résolution.",
    },
    {
        "sequence_code": "course_start",
        "step_index": 1,
        "delay": "J-14",
        "template_name": "demo_cours_j14",
        "meaning": "Relance cours deux semaines avant le début.",
    },
    {
        "sequence_code": "course_start",
        "step_index": 2,
        "delay": "J-7",
        "template_name": "demo_cours_j7",
        "meaning": "Relance cours une semaine avant le début.",
    },
    {
        "sequence_code": "course_start",
        "step_index": 3,
        "delay": "J-3",
        "template_name": "demo_cours_j3",
        "meaning": "Relance cours trois jours avant le début.",
    },
    {
        "sequence_code": "course_start",
        "step_index": 4,
        "delay": "J-1",
        "template_name": "demo_cours_j1",
        "meaning": "Relance cours la veille du début.",
    },
]

MAIN_ACTION_TYPES = [
    {
        "type": "reply",
        "label": "Répondre",
        "meaning": "Répondre à un message entrant WhatsApp.",
        "default_owner": "Setter 1",
        "expected_proof": "Message WhatsApp sortant après le message entrant.",
    },
    {
        "type": "follow_up",
        "label": "Relancer",
        "meaning": "Relancer le prospect, souvent via template WhatsApp.",
        "default_owner": "Setter 2",
        "expected_proof": "Message libre ou template de relance envoyé.",
    },
    {
        "type": "setting_call",
        "label": "Appel de setting",
        "meaning": "Appeler pour qualifier et obtenir la suite commerciale.",
        "default_owner": "Setter 1",
        "expected_proof": "Résultat d'appel, mini note et qualification setter.",
    },
    {
        "type": "closing_call",
        "label": "Appel de closing",
        "meaning": "Appeler pour vendre, finaliser ou trancher.",
        "default_owner": "Closer",
        "expected_proof": "Résultat d'appel, mini note et qualification closer.",
    },
]

SUPPORT_ACTIONS = [
    {
        "support": "Qualification",
        "role": "Résultat métier qui influence le chaînage. La qualification closer prime sur celle du setter.",
        "queue_visible_when": "Seulement si une revue de qualification bloque le flux.",
    },
    {
        "support": "Statut de contact",
        "role": "Décide si le prospect peut encore être contacté.",
        "queue_visible_when": "Quand un prospect Ne plus contacter réécrit et nécessite une revue Setter 1.",
    },
    {
        "support": "Note manuelle",
        "role": "Preuve ou contexte après appel, échange privé ou décision.",
        "queue_visible_when": "Seulement si une documentation obligatoire manque.",
    },
    {
        "support": "Création de template",
        "role": "Débloque une relance quand aucun template approuvé ne convient.",
        "queue_visible_when": "Quand une relance est bloquée par template manquant.",
    },
    {
        "support": "Revue admin",
        "role": "Cas ambigu, conflit de règles ou donnée manquante.",
        "queue_visible_when": "Quand le système ne peut pas choisir la prochaine action.",
    },
]

ACTION_STATUSES = [
    {
        "status": "planned",
        "label": "Planifiée",
        "meaning": "Action prévue plus tard.",
        "is_terminal": False,
    },
    {
        "status": "open",
        "label": "Ouverte",
        "meaning": "Action active.",
        "is_terminal": False,
    },
    {
        "status": "in_progress",
        "label": "En cours",
        "meaning": "Quelqu'un a pris l'action en main.",
        "is_terminal": False,
    },
    {
        "status": "done",
        "label": "Terminée",
        "meaning": "Action terminée avec preuve ou résultat.",
        "is_terminal": True,
    },
    {
        "status": "cancelled",
        "label": "Annulée",
        "meaning": "Action remplacée, rendue inutile ou annulée par une règle.",
        "is_terminal": True,
    },
    {
        "status": "blocked",
        "label": "Bloquée",
        "meaning": "Action impossible tant qu'un blocage n'est pas levé.",
        "is_terminal": False,
    },
]

WORKFLOW_TRANSITIONS = [
    {
        "current_action": "Aucune",
        "trigger": "web_form_submitted_then_schooldrive_lead_created",
        "outcome": "SchoolDrive crée un Lead ou une Préinscription et envoie le WhatsApp automatique initial",
        "next_action": "follow_up",
        "owner": "Setter 2",
        "due": "+72h après le WhatsApp automatique initial",
        "conversation": "Ouverte",
        "required_support": "Identifiant SchoolDrive, type lead/presubscription, source paid_ads/organic",
        "side_effects": "Stocker l'événement initial et annuler cette relance si le prospect répond avant échéance",
    },
    {
        "current_action": "follow_up",
        "trigger": "initial_message_no_reply_after_72h",
        "outcome": "Le prospect n'a pas répondu au WhatsApp automatique initial",
        "next_action": "follow_up",
        "owner": "Setter 2",
        "due": "Maintenant",
        "conversation": "Ouverte",
        "required_support": "Relire conversation, choisir template approuvé ou créer template_request",
        "side_effects": "Respecter délai minimum 24h entre relances WhatsApp",
    },
    {
        "current_action": "Toute action non terminale",
        "trigger": "prospect_replied",
        "outcome": "Dernier message entrant non répondu et contact autorisé",
        "next_action": "reply",
        "owner": "Setter 1",
        "due": "Maintenant",
        "conversation": "Ouverte",
        "required_support": "Aucun",
        "side_effects": "Hot signal, file Setter 1, annuler relances futures",
    },
    {
        "current_action": "Toute action non terminale",
        "trigger": "do_not_contact_prospect_replied",
        "outcome": "Le prospect est Ne plus contacter mais réécrit",
        "next_action": "contact_review",
        "owner": "Setter 1",
        "due": "Maintenant",
        "conversation": "Ouverte",
        "required_support": "Revue humaine obligatoire",
        "side_effects": "Aucune relance automatique tant que le blocage n'est pas levé",
    },
    {
        "current_action": "reply",
        "trigger": "outbound_message_sent",
        "outcome": "Réponse envoyée sans RDV",
        "next_action": "follow_up",
        "owner": "Setter 2",
        "due": "+72h après le dernier message sortant",
        "conversation": "Ouverte",
        "required_support": "Message sortant",
        "side_effects": "Supprimer hot signal",
    },
    {
        "current_action": "reply",
        "trigger": "setting_appointment_booked",
        "outcome": "RDV setting fixé",
        "next_action": "setting_call",
        "owner": "Setter 1",
        "due": "Date/heure RDV",
        "conversation": "Ouverte",
        "required_support": "Message sortant, RDV noté",
        "side_effects": "Annuler relance de sécurité",
    },
    {
        "current_action": "reply",
        "trigger": "written_exchange_terminal",
        "outcome": "Prospect non pertinent ou Ne plus contacter",
        "next_action": "Aucune",
        "owner": "Personne",
        "due": "Aucun",
        "conversation": "Résolue",
        "required_support": "Qualification ou statut de contact",
        "side_effects": "Stopper relances",
    },
    {
        "current_action": "follow_up",
        "trigger": "follow_up_due",
        "outcome": "Fenêtre WhatsApp ouverte",
        "next_action": "Selon résultat de l'envoi",
        "owner": "Setter 2",
        "due": "Maintenant",
        "conversation": "Ouverte",
        "required_support": "Message libre ou template",
        "side_effects": "Respecter délai minimum",
    },
    {
        "current_action": "follow_up",
        "trigger": "follow_up_due",
        "outcome": "Fenêtre WhatsApp fermée, template disponible",
        "next_action": "Selon résultat de l'envoi",
        "owner": "Setter 2",
        "due": "Maintenant",
        "conversation": "Ouverte",
        "required_support": "Template approuvé",
        "side_effects": "Respecter délai minimum",
    },
    {
        "current_action": "follow_up",
        "trigger": "follow_up_due_template_missing",
        "outcome": "Fenêtre fermée et aucun template adapté",
        "next_action": "follow_up bloquée",
        "owner": "Setter 2",
        "due": "Maintenant",
        "conversation": "Ouverte",
        "required_support": "template_request",
        "side_effects": "Action principale passe blocked et reste liée à la demande de template",
    },
    {
        "current_action": "template_request",
        "trigger": "template_submitted",
        "outcome": "Nouveau template soumis à validation",
        "next_action": "follow_up reste bloquée",
        "owner": "Setter 2",
        "due": "Dès approbation",
        "conversation": "Ouverte",
        "required_support": "Statut Twilio/Meta",
        "side_effects": "Surveiller statut template",
    },
    {
        "current_action": "template_request",
        "trigger": "template_approved",
        "outcome": "Relance débloquée",
        "next_action": "follow_up",
        "owner": "Setter 2",
        "due": "Maintenant",
        "conversation": "Ouverte",
        "required_support": "Template approuvé",
        "side_effects": "Débloquer action principale",
    },
    {
        "current_action": "follow_up",
        "trigger": "outbound_template_sent",
        "outcome": "Relance envoyée, séquence non terminée",
        "next_action": "follow_up",
        "owner": "Setter 2",
        "due": "Selon prochaine étape de séquence",
        "conversation": "Ouverte",
        "required_support": "Message sortant",
        "side_effects": "Incrémenter séquence",
    },
    {
        "current_action": "follow_up",
        "trigger": "outbound_template_sent_last_step",
        "outcome": "Dernière relance de séquence envoyée sans réponse",
        "next_action": "Aucune",
        "owner": "Personne",
        "due": "Aucun",
        "conversation": "Résolue",
        "required_support": "Message sortant",
        "side_effects": "Motif résolution sequence_completed_no_reply",
    },
    {
        "current_action": "setting_call",
        "trigger": "setting_call_completed",
        "outcome": "À closer",
        "next_action": "closing_call",
        "owner": "Closer",
        "due": "Date RDV ou maintenant",
        "conversation": "Ouverte",
        "required_support": "Mini note, qualification setter",
        "side_effects": "Lead passe en closing",
    },
    {
        "current_action": "setting_call",
        "trigger": "setting_call_not_reached",
        "outcome": "Prospect non joint",
        "next_action": "setting_call puis follow_up si rappels épuisés",
        "owner": "Setter 1 puis Setter 2",
        "due": "+2h ouvrées, +24h ouvrées, puis +72h",
        "conversation": "Ouverte",
        "required_support": "Mini note d'appel",
        "side_effects": "Encoder tentative d'appel et compteur de rappel",
    },
    {
        "current_action": "setting_call",
        "trigger": "setting_call_completed_no_next_step",
        "outcome": "Prospect joint mais pas prêt ou pas de suite claire",
        "next_action": "follow_up",
        "owner": "Setter 2",
        "due": "+72h après l'appel",
        "conversation": "Ouverte",
        "required_support": "Mini note",
        "side_effects": "Séquence setter_no_next_step",
    },
    {
        "current_action": "setting_call",
        "trigger": "setting_call_terminal",
        "outcome": "Non pertinent ou Ne plus contacter",
        "next_action": "Aucune",
        "owner": "Personne",
        "due": "Aucun",
        "conversation": "Résolue",
        "required_support": "Mini note, qualification ou statut de contact",
        "side_effects": "Stopper relances",
    },
    {
        "current_action": "closing_call",
        "trigger": "closing_call_completed",
        "outcome": "Signé",
        "next_action": "Aucune",
        "owner": "Personne",
        "due": "Aucun",
        "conversation": "Résolue",
        "required_support": "Mini note, qualification closer signed",
        "side_effects": "Vente gagnée, stopper relances",
    },
    {
        "current_action": "closing_call",
        "trigger": "closing_call_completed",
        "outcome": "Va signer",
        "next_action": "follow_up",
        "owner": "Setter 2",
        "due": "+72h puis séquence closer_will_sign",
        "conversation": "Ouverte",
        "required_support": "Mini note, qualification closer will_sign",
        "side_effects": "Séquence closer_will_sign",
    },
    {
        "current_action": "closing_call",
        "trigger": "closing_call_not_reached",
        "outcome": "Prospect non joint",
        "next_action": "closing_call puis follow_up si rappels épuisés",
        "owner": "Closer puis Setter 2",
        "due": "+2h ouvrées, +24h ouvrées, puis +72h",
        "conversation": "Ouverte",
        "required_support": "Mini note d'appel",
        "side_effects": "Encoder tentative d'appel et compteur de rappel",
    },
    {
        "current_action": "closing_call",
        "trigger": "closing_call_completed_undecided",
        "outcome": "Prospect joint mais pas de décision claire",
        "next_action": "follow_up",
        "owner": "Setter 2",
        "due": "+72h après l'appel",
        "conversation": "Ouverte",
        "required_support": "Mini note",
        "side_effects": "Séquence post_call_undecided",
    },
    {
        "current_action": "closing_call",
        "trigger": "closing_call_terminal",
        "outcome": "Non pertinent",
        "next_action": "Aucune",
        "owner": "Personne",
        "due": "Aucun",
        "conversation": "Résolue",
        "required_support": "Mini note, qualification closer not_relevant",
        "side_effects": "Stopper relances",
    },
    {
        "current_action": "follow_up lead-relative",
        "trigger": "course_start_approaching",
        "outcome": "Lead non signé, date de cours connue",
        "next_action": "follow_up cours",
        "owner": "Setter 2 ou IA",
        "due": "J-14/J-7/J-3/J-1",
        "conversation": "Ouverte",
        "required_support": "Template cours",
        "side_effects": "Annuler la relance lead-relative concurrente",
    },
    {
        "current_action": "Toute action",
        "trigger": "terminal_status_applied",
        "outcome": "not_relevant, do_not_contact ou signed",
        "next_action": "Aucune",
        "owner": "Personne",
        "due": "Aucun",
        "conversation": "Résolue",
        "required_support": "Qualification ou statut de contact",
        "side_effects": "Stopper relances",
    },
    {
        "current_action": "Toute action",
        "trigger": "conversation_resolved",
        "outcome": "Utilisateur clôture avec motif obligatoire",
        "next_action": "Aucune",
        "owner": "Personne",
        "due": "Aucun",
        "conversation": "Résolue",
        "required_support": "Motif de résolution, note si motif l'exige",
        "side_effects": "Historiser résolution et fermer actions ouvertes",
    },
    {
        "current_action": "Aucune",
        "trigger": "conversation_reopened",
        "outcome": "Utilisateur rouvre",
        "next_action": "Action principale obligatoire",
        "owner": "Utilisateur courant ou responsable choisi",
        "due": "Maintenant ou planifié",
        "conversation": "Ouverte",
        "required_support": "Raison de réouverture",
        "side_effects": "Interdire conversation ouverte sans action",
    },
    {
        "current_action": "Toute action",
        "trigger": "business_hours_closed",
        "outcome": "Prospect écrit hors disponibilité",
        "next_action": "reply planifiée",
        "owner": "Backup ou prochain créneau",
        "due": "Prochain créneau ouvré",
        "conversation": "Ouverte",
        "required_support": "Option template hors horaire",
        "side_effects": "Message automatique possible",
    },
    {
        "current_action": "Toute action",
        "trigger": "assignee_unavailable",
        "outcome": "Responsable absent",
        "next_action": "Même action transférée",
        "owner": "Backup",
        "due": "Même échéance ou prochain créneau",
        "conversation": "Inchangée",
        "required_support": "Règle de backup",
        "side_effects": "Historiser transfert",
    },
]

LEAD_TYPES = [
    {
        "type": "lead",
        "label": "Lead",
        "source": "Demande d'information sans session pré-sélectionnée, généralement paid ads.",
        "course_date_rule": "Utiliser la prochaine session pertinente depuis SchoolDrive, à confirmer.",
    },
    {
        "type": "presubscription",
        "label": "Préinscription",
        "source": "Le prospect a pré-sélectionné une session, généralement via recherche naturelle.",
        "course_date_rule": "Utiliser la date de cette session SchoolDrive.",
    },
]

DEMO_TEMPLATE_CATALOG = [
    {
        "name": "demo_initial_offer",
        "category": "marketing",
        "body": "Bonjour {{first_name}}, merci pour votre demande concernant {{course_title}}. Nous avons actuellement une offre spéciale. Répondez à ce message et je vous donne les détails. Yasmine",
        "sequence": "lead_created",
    },
    {
        "name": "demo_relance_72h_1",
        "category": "marketing",
        "body": "Bonjour {{first_name}}, je me permets de revenir vers vous au sujet de {{course_title}}. Souhaitez-vous recevoir les informations pratiques ? Yasmine",
        "sequence": "lead_no_reply",
    },
    {
        "name": "demo_relance_72h_2",
        "category": "marketing",
        "body": "Bonjour {{first_name}}, avez-vous encore un intérêt pour la formation {{course_title}} ? Je peux vous orienter rapidement. Yasmine",
        "sequence": "lead_no_reply",
    },
    {
        "name": "demo_relance_72h_3",
        "category": "marketing",
        "body": "Bonjour {{first_name}}, je vous relance une dernière fois cette semaine pour {{course_title}}. Souhaitez-vous que l'on vous appelle ? Yasmine",
        "sequence": "lead_no_reply",
    },
    {
        "name": "demo_relance_7j_1",
        "category": "marketing",
        "body": "Bonjour {{first_name}}, les inscriptions avancent pour {{course_title}}. Voulez-vous que je vérifie les possibilités pour vous ? Yasmine",
        "sequence": "lead_no_reply",
    },
    {
        "name": "demo_relance_7j_2",
        "category": "marketing",
        "body": "Bonjour {{first_name}}, je reviens vers vous concernant votre demande ESSR. Souhaitez-vous toujours des informations ? Yasmine",
        "sequence": "lead_no_reply",
    },
    {
        "name": "demo_relance_30j_stop",
        "category": "marketing",
        "body": "Bonjour {{first_name}}, je clôture votre demande pour le moment. Si vous souhaitez reprendre le sujet, répondez simplement à ce message. Yasmine",
        "sequence": "lead_no_reply",
    },
    {
        "name": "demo_relance_setting_72h_1",
        "category": "utility",
        "body": "Bonjour {{first_name}}, je reviens vers vous après notre échange concernant {{course_title}}. Souhaitez-vous que l'on fixe un moment ? Yasmine",
        "sequence": "setter_no_next_step",
    },
    {
        "name": "demo_relance_setting_72h_2",
        "category": "utility",
        "body": "Bonjour {{first_name}}, avez-vous pu réfléchir à la suite pour {{course_title}} ? Je peux vous aider à avancer. Yasmine",
        "sequence": "setter_no_next_step",
    },
    {
        "name": "demo_relance_setting_72h_3",
        "category": "utility",
        "body": "Bonjour {{first_name}}, je vous relance concernant notre échange sur {{course_title}}. Souhaitez-vous être rappelé ? Yasmine",
        "sequence": "setter_no_next_step",
    },
    {
        "name": "demo_relance_setting_7j_1",
        "category": "utility",
        "body": "Bonjour {{first_name}}, je reviens vers vous une semaine après notre échange. Souhaitez-vous reprendre le sujet ? Yasmine",
        "sequence": "setter_no_next_step",
    },
    {
        "name": "demo_relance_setting_7j_2",
        "category": "utility",
        "body": "Bonjour {{first_name}}, souhaitez-vous encore que l'on vous accompagne pour {{course_title}} ? Yasmine",
        "sequence": "setter_no_next_step",
    },
    {
        "name": "demo_relance_setting_30j_stop",
        "category": "utility",
        "body": "Bonjour {{first_name}}, je clôture le suivi pour le moment. Vous pouvez me répondre si vous souhaitez reprendre. Yasmine",
        "sequence": "setter_no_next_step",
    },
    {
        "name": "demo_setting_rdv",
        "category": "utility",
        "body": "Bonjour {{first_name}}, êtes-vous disponible demain pour un court appel ? Mon collègue pourra vous présenter la formation {{course_title}}. Yasmine",
        "sequence": "setter_conversation",
    },
    {
        "name": "demo_va_signer_72h_1",
        "category": "utility",
        "body": "Bonjour {{first_name}}, je reviens vers vous pour finaliser votre inscription à {{course_title}}. Avez-vous besoin d'aide pour la dernière étape ? Yasmine",
        "sequence": "closer_will_sign",
    },
    {
        "name": "demo_va_signer_72h_2",
        "category": "utility",
        "body": "Bonjour {{first_name}}, je voulais vérifier si tout est bon pour finaliser votre inscription à {{course_title}}. Yasmine",
        "sequence": "closer_will_sign",
    },
    {
        "name": "demo_va_signer_72h_3",
        "category": "utility",
        "body": "Bonjour {{first_name}}, souhaitez-vous que je vous aide à terminer votre inscription aujourd'hui ? Yasmine",
        "sequence": "closer_will_sign",
    },
    {
        "name": "demo_va_signer_7j_1",
        "category": "utility",
        "body": "Bonjour {{first_name}}, je reviens vers vous concernant la finalisation de {{course_title}}. Yasmine",
        "sequence": "closer_will_sign",
    },
    {
        "name": "demo_va_signer_7j_2",
        "category": "utility",
        "body": "Bonjour {{first_name}}, dois-je garder votre dossier ouvert pour {{course_title}} ? Yasmine",
        "sequence": "closer_will_sign",
    },
    {
        "name": "demo_va_signer_30j_stop",
        "category": "utility",
        "body": "Bonjour {{first_name}}, sans retour de votre part je clôture le suivi. Répondez-moi si vous souhaitez reprendre. Yasmine",
        "sequence": "closer_will_sign",
    },
    {
        "name": "demo_cours_j14",
        "category": "marketing",
        "body": "Bonjour {{first_name}}, la session {{course_title}} démarre dans deux semaines. Souhaitez-vous que je vérifie les possibilités pour vous ? Yasmine",
        "sequence": "course_start",
    },
    {
        "name": "demo_cours_j7",
        "category": "marketing",
        "body": "Bonjour {{first_name}}, la session {{course_title}} commence bientôt. Souhaitez-vous encore recevoir les informations ? Yasmine",
        "sequence": "course_start",
    },
    {
        "name": "demo_cours_j3",
        "category": "marketing",
        "body": "Bonjour {{first_name}}, la session {{course_title}} commence bientôt. Souhaitez-vous que je vérifie s'il reste une possibilité pour vous ? Yasmine",
        "sequence": "course_start",
    },
    {
        "name": "demo_cours_j1",
        "category": "marketing",
        "body": "Bonjour {{first_name}}, la session {{course_title}} commence demain. Souhaitez-vous un dernier point rapide ? Yasmine",
        "sequence": "course_start",
    },
    {
        "name": "demo_hors_horaire",
        "category": "utility",
        "body": "Bonjour {{first_name}}, merci pour votre message. L'équipe est actuellement indisponible, nous vous répondrons au prochain créneau ouvré. Yasmine",
        "sequence": "out_of_hours",
    },
]
